
settings: 
    
    # Steering rack calibrations
    steering rack: 
        
        # Motor position in range [0,120] corresponding to centered steering rack
        center: 52
      
    
    # Camera calibrations
    camera:

        # Camera offsets from center, expressed as percent
        # =0% --> Camera is exactly in the middle.
        # >0% --> Camera is skewed towards the left.
        # <0% --> Camera is skewed towards the right.

        # Offset of front camera
        front offset: 0.02
        # Offset of rear camera
        rear offset: 0.02
        #Framerate for OpenCV recording (this seems to produce wildly inconsistent result)
        framerate: 10

    #Driving settings
    driving: 
        sharp turn threshold: 7.5
        #threshold of front
        sharp turn reverse threshold: 20
        #threshold of back
        position threshold : 0.03125        #1/60
        #angle of trailer relative to center of lane
        trailer angle off center threshold : 1
        #amount of degrees before trailer correction
        hitch angle threshold : 1
        
        turn ratio : 2.5

    #Streaming settings
    streaming:
        #Enable or disable streaming
        enabled: true
        #Streaming destination IP address
        destination ip: "192.168.2.185"
        #Streaming destination port. Client is preconfigured with port 25565 by default. 
        destination port: 25565



    
    
