
settings:

    gpio:

        # GPIO pin controlling drive motor power
        drive motor power: 25
        # GPIO pin controlling forward driving
        drive motor forward: 6
        # GPIO pin controlling reverse driving
        drive motor reverse: 5
        # GPIO pin controlling steering rack servo
        servo motor: 4

    
    # Steering rack calibrations
    steering rack: 
        
        # Motor position in range [0,120] corresponding to centered steering rack
        center: 52
      
    
    # Camera calibrations
    camera:



   
        # Framerate for OpenCV recording (this seems to produce wildly inconsistent result)
        framerate: 60
        # NOTE: I would not reccomend changing the resolution as no resolutions have been tested other than 800x600
        resolution width: 800
        resolution height: 600


    #Streaming settings
    streaming:
        #Enable or disable streaming
        enabled: true
        #Streaming destination IP address. UDP Streaming also always streams to localhost.
        destination ip: "192.168.2.185"
        #Streaming destination port. Client is preconfigured with port 25565 by default. 
        destination port: 25565
     
    
    control:
    #0 for controller, 1 for phone
        control mode: 1



    
    