markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
title: TrailerBackerUpper
description: Autonomous Truck and Trailer - Documentation
