
calibrations: 
    
    # Steering rack calibrations
    steering rack: 
        
        # Motor position in range [0,180] corresponding to centered steering rack
        center: 86
        # Right bound of steering rack, expressed in degrees from center
        right: 30
        # Left bound of steering rack, expressed in degrees from center
        left: 40
    
    # Camera calibrations
    camera:

        # Camera offsets from center, expressed as percent
        # =0% --> Camera is exactly in the middle.
        # >0% --> Camera is skewed towards the left.
        # <0% --> Camera is skewed towards the right.

        # Offset of front camera
        front offset: 0.02
        # Offset of rear camera
        rear offset: 0.02
        #Framerate for OpenCV recording (this seems to produce wildly inconsistent result)
        framerate: 15
    
    driving: 
        sharp turn threshold: 7.5
        #threshold of front
        sharp turn reverse threshold: 20
        #threshold of back
        position threshold : 0.03125        #
        trailer angle off center threshold : 1
        #angle of trailer relative to center of lane
        hitch angle threshold : 1
        #amount of degrees before trailer correction
        turn ratio : 2.5
        #



    
    
